source('scripts/generateSimuData.R')
source('scripts/implementClusterMethods.R')
source('scripts/dataProcessing.R')



## generate simulation from PBMC10kb data -- not used ####

# read filterd data
mtx = readRDS('data/intermediate/Filtered_mat/PBMC10k_filtered_mat.rds')

# further filtering for simulation
depth.cell = Matrix::colSums(mtx)
mtx = mtx[, depth.cell > 4000]

# only keep top 20% of features for generating simulation data
seurat.obj = CreateSeuratObject(mtx, assay = 'ATAC')

seurat.obj <- FindVariableFeatures(object = seurat.obj, 
                                   selection.method = 'vst', 
                                   nfeatures = floor(nrow(mtx) * 0.2))
sele.features = VariableFeatures(seurat.obj)

mtx = mtx[rownames(mtx) %in% sele.features, ]

saveRDS(mtx, 'data/intermediate/Filtered_mat/PBMC10k_filtered_mat4simu.rds')



## relatively easy data ####
mtx = readRDS('data/intermediate/Filtered_mat/PBMC10k_filtered_mat4simu.rds')

simu.data <- generateSCAtac_splatter(as.matrix(mtx), group.prob = rep(0.2, 5),
                                     de.prob = rep(0.3, 5), params = NULL,
                                     ncells = 5000, npeaks = 5000, isNorm = F)

saveRDS(simu.data, 'data/intermediate/Filtered_mat/PBMC10k_simuData.rds')

#updat parameters and simulate again (which is much fast if params is given)
simu.data = readRDS('data/intermediate/Filtered_mat/PBMC10k_simuData.rds')
params = simu.data$params
params@lib.scale = 0.05

simu.data <- generateSCAtac_splatter(as.matrix(mtx), group.prob = rep(0.2, 5),
                                     de.prob = rep(0.2, 5), params = params,
                                     ncells = 5000, npeaks = nrow(mtx), isNorm = F)
rownames(simu.data$mtx) = rownames(mtx)
simu.data$mtx = filterMat(simu.data$mtx)
simu.data$cluster_labels = simu.data$cluster_labels[rownames(simu.data$cluster_labels) %in% colnames(simu.data$mtx),]
saveRDS(simu.data, 'data/intermediate/Filtered_mat/PBMC10k_simuData.rds')



## plot to see seperation

simu.seurat <- doBasicSeurate(simu.data$mtx, doLog = F, regr.var = NULL, 
                              top.variable = 1)
simu.seurat@meta.data[['group']] = simu.data$cluster_labels$Group

simu.seurat <- RunUMAP(simu.seurat, dims = 1:50)
simu.seurat <- RunTSNE(simu.seurat, dims = 1:50)


postscript(file = 'output/figures/simulated_easyData_drPlot.eps',
           width = 8, height = 3.5)

p1 = DimPlot(simu.seurat, reduction = 'tsne', group.by = 'group')
p2 = DimPlot(simu.seurat, reduction = 'umap', group.by = 'group')
ggpubr::ggarrange(p1, p2, nrow = 1, ncol = 2)
dev.off()


cor(simu.seurat@meta.data$nCount_ATAC, 
    simu.seurat@reductions$pca@cell.embeddings[,1])



## harder data ####
simu.data <- generateSCAtac_splatter(as.matrix(mtx), group.prob = c(0.1, 0.1, 0.3, 0.1, 0.4),
                                     de.prob = rep(0.2, 5), params = params,
                                     ncells = 5000, npeaks = nrow(mtx), isNorm = F)
rownames(simu.data$mtx) = rownames(mtx)
simu.data$mtx = filterMat(simu.data$mtx)
simu.data$cluster_labels = simu.data$cluster_labels[rownames(simu.data$cluster_labels) %in% colnames(simu.data$mtx),]

saveRDS(simu.data, 'data/intermediate/Filtered_mat/PBMC10k_simuData_hard.rds')


simu.data = readRDS('data/intermediate/Filtered_mat/PBMC10k_simuData_hard.rds')


simu.seurat <- doBasicSeurate(simu.data$mtx, doLog = F, regr.var = NULL, 
                              top.variable = 1)
simu.seurat@meta.data[['group']] = simu.data$cluster_labels$Group

simu.seurat <- RunUMAP(simu.seurat, dims = 1:50)
simu.seurat <- RunTSNE(simu.seurat, dims = 1:50)


postscript(file = 'output/figures/simulated_hardData_drPlot.eps',
           width = 8, height = 3.5)
p1 = DimPlot(simu.seurat, reduction = 'tsne', group.by = 'group')
p2 = DimPlot(simu.seurat, reduction = 'umap', group.by = 'group')
ggpubr::ggarrange(p1, p2, nrow = 1, ncol = 2)
dev.off()



cor(simu.seurat@meta.data$nCount_ATAC, 
    simu.seurat@reductions$pca@cell.embeddings[,1])





## resample data from blood cells, bulk ATAC of GSE74912 ####
## the raw matrix was generated by customized script in
## /scr1/users/yuw1/Data/scAnalysis/ATAC/GSE74912
mtx = readRDS('data/raw/resample_hsc/resample10k_hsc_raw_mat.rds')

mtx.filter = filterMat(mtx, min_depth = 100)

rnames = rownames(mtx.filter)
mtx.filter = mtx.filter[grepl(rnames, pattern = '^chr'), ]
saveRDS(mtx.filter, 'data/intermediate/Filtered_mat/resample10k_hsc_filtered_mat.rds')

# visualize data
library(ggplot2)
mtx.filter = readRDS('data/intermediate/Filtered_mat/resample10k_hsc_filtered_mat.rds')

seurat.obj = doBasicSeurate(mtx.filter, top.variable = 1, doScale = F, doCenter = F, 
                            doLog = F, regr.var = NULL)

seurat.obj = RunTSNE(seurat.obj, dims = 1:50)
seurat.obj = RunUMAP(seurat.obj, dims = 1:50)
cnames = colnames(mtx.filter)
true.label = sapply(cnames, function(x) unlist(strsplit(x, '-'))[1])

seurat.obj@meta.data$sort_label = true.label

dtype = 'resample10k_hsc'

postscript(file = paste0('output/figures/', dtype, '_drPlot.eps'),
           width = 6, height = 5)
DimPlot(seurat.obj, reduction = 'umap', group.by = 'sort_label')
dev.off()

## alternatively -- not used
res.dr = doDimReduction4mat(mtx.filter, max_pc = 50, doTSNE = T)
tsne.coords = data.table(res.dr$tsne_coords, keep.rownames = T)
tsne.coords[, 'sort_label' := unlist(strsplit(rn, '-'))[1], by = rn]
ggplot(data = tsne.coords, aes(x = tsne_1, y = tsne_2, col = sort_label)) + geom_point()


tsne.coords = Rtsne(t(as.matrix(mtx.filter)))


## synthetic data from blood cells, bulk ATAC of GSE96771 ####
## the synthetic data with different noise level was downloaded from
## https://github.com/pinellolab/scATAC-benchmarking/blob/master/Synthetic_Data/
bm.noise2 = readRDS('data/raw/GSE96771/bonemarrow_noisy_p2.rds')
cn = colnames(bm.noise2)
ctype = sapply(cn, function(x) unlist(strsplit(x, '_'))[1])


## generate synthetic data with noise using resample10k_hsc data (GSE74912) ####
## stratege 1 -- simulate from the original bulk matrix
meta = fread('data/raw/GSE74912/srrInfo4Download.txt')
counts = fread('data/raw/GSE74912/GSE74912_ATACseq_All_Counts.txt')
cn = colnames(counts)
counts0 = subset(counts, select = meta$V4)


## stratege 2 -- for the aggregated resample10k_hsc data
mtx = readRDS('data/intermediate/Filtered_mat/resample10k_hsc_filtered_mat.rds')
cn = colnames(mtx)
ctype = sapply(cn, function(x) unlist(strsplit(x, '-'))[1])
uctype = unique(ctype)

# construct the aggregated matrix
bulk.mtx = lapply(uctype, function(x) Matrix::rowSums(mtx[, grepl(cn, pattern = x)]))
bulk.mtx = do.call('cbind', bulk.mtx)
colnames(bulk.mtx) = uctype

mtx.clean <- simulate_scatac(bulk = bulk.mtx, n_cells = 200, 
                             which_celltypes = uctype, n_frags_per_cell = 1000, 
                             rate_noise = 0, seed = 100, shuffle = FALSE)

mtx.noisy2 <- simulate_scatac(bulk = bulk.mtx, n_cells = 200, 
                             which_celltypes = uctype, n_frags_per_cell = 1000, 
                             rate_noise = 0.2, seed = 100, shuffle = FALSE)
 
mtx.noisy4 <- simulate_scatac(bulk = bulk.mtx, n_cells = 200, 
                             which_celltypes = uctype, n_frags_per_cell = 1000, 
                             rate_noise = 0.4, seed = 100, shuffle = FALSE)

saveRDS(mtx.clean, file = 'data/intermediate/Filtered_mat/resample10k_hsc_clean_filtered_mat.rds')
saveRDS(mtx.noisy2, file = 'data/intermediate/Filtered_mat/resample10k_hsc_noisy_q2_filtered_mat.rds')
saveRDS(mtx.noisy4, file = 'data/intermediate/Filtered_mat/resample10k_hsc_noisy_q4_filtered_mat.rds')

